FROM ubuntu:mantic

RUN echo "VERSION 0.0.3" > /var/version

# Add China Mirror to speed up local build process
COPY sources.cn /etc/apt/sources.list

# Install necessary dependencies
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y cmake git curl zip unzip tar
RUN apt-get install -y gcc-12 g++-12
RUN apt-get install -y gdb

# Mark g++-12 as default C++ compiler
WORKDIR /usr/bin
RUN ln -s g++-12 g++

# Install vcpkg as C++ package manager
WORKDIR /usr/local
RUN git clone --depth=1 https://github.com/Microsoft/vcpkg.git && \
    ./vcpkg/bootstrap-vcpkg.sh
ENV VCPKG_ROOT /usr/local/vcpkg
ENV PATH $VCPKG_ROOT:$PATH

# Install packages needed
RUN apt-get install -y pkg-config 
RUN vcpkg install catch2

# Install wfrest RESTFUL framework
# ENV DEBIAN_FRONTEND=noninteractive
# RUN apt-get update \
#     && apt-get install -y vim make libssl-dev libgtest-dev zlib1g-dev \
#     && apt-get clean && rm -rf /var/lib/apt/lists/* \
#     && git clone https://github.com/sogou/workflow.git \ 
#     && cd workflow && make -j && make install \
#     && cd .. && rm -rf workflow \ 
#     && git clone https://github.com/wfrest/wfrest.git \
#     && cd wfrest && mkdir build && cd build \
#     && cmake .. && make -j && make install 
# ENV LD_LIBRARY_PATH /usr/local/lib