FROM ubuntu:mantic

RUN echo "VERSION 0.0.5" > /var/version

# Add China Mirror to speed up local build process
COPY sources.cn /etc/apt/sources.list

# Install necessary dependencies
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y cmake git curl zip unzip tar \
    gcc-12 g++-12 gdb \
    clang-format \
    pkg-config \ 
    flex bison \
    golang

# Install vcpkg as C++ package manager
WORKDIR /usr/local
RUN git clone --depth=1 https://github.com/Microsoft/vcpkg.git && \
    ./vcpkg/bootstrap-vcpkg.sh
ENV VCPKG_ROOT /usr/local/vcpkg
ENV PATH $VCPKG_ROOT:$PATH

# Install packages needed
RUN vcpkg install catch2
RUN vcpkg install boost-json