name: C++ Build and Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest
    # using latest development file
    container: 
      image: distinctwind/visual-decaf:latest
    steps:
      - name: Checkout this Repo
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake --preset "debug" -S . -B build

      - name: Build All Targets
        run: cmake --build build
      
      - name: Run Unit Tests
        run: ctest
        working-directory: ./build
